SRC_DIR = ../src
DEPS_DIR = ../platforms/shared/dependencies
TEST_SRC_DIR=.

SOURCES_C := \
    $(DEPS_DIR)/miniz/miniz.c \

SOURCES_CXX := \
    $(TEST_SRC_DIR)/main.cpp \
    $(SRC_DIR)/audio.cpp \
    $(SRC_DIR)/bus.cpp \
    $(SRC_DIR)/gearlynx_core.cpp \
    $(SRC_DIR)/input.cpp \
    $(SRC_DIR)/m6502.cpp \
    $(SRC_DIR)/m6502_functors.cpp \
    $(SRC_DIR)/m6502_opcodes.cpp \
    $(SRC_DIR)/lcd_screen.cpp \
    $(SRC_DIR)/media.cpp \
    $(SRC_DIR)/memory.cpp \
    $(SRC_DIR)/mikey.cpp \
    $(SRC_DIR)/suzy.cpp \
    $(SRC_DIR)/eeprom.cpp \
    $(SRC_DIR)/vgm_recorder.cpp
